#drivers/input/touchscreen/focaltech_touch/focaltech_test
#
#Makefile for test module
#
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/

obj-y	+= focaltech_test.o
obj-y	+= focaltech_test_main.o
obj-y	+= focaltech_test_ini.o
obj-y	+= focaltech_test_global.o
obj-y	+= focaltech_test_detail_threshold.o
obj-y	+= focaltech_test_config_ft8607.o
obj-y	+= focaltech_test_ft8607.o
